language: bash

services:
  - docker

script:
  - git clone https://github.com/keboola/ex-generic-mock-server.git ./server/
  - rm -rf ./server/data/
  - git clone https://github.com/keboola/app-generic-faker-data.git ./server/data/
  - docker build --tag=mock-server ./server/

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh

notifications:
  email: false
  slack:
    secure: UOgxCPPafLQYhpViZLP/rKtvKe1vOmdInk/C3UBZxw9UBH41rSNtg20KpNdToNPVVx5qfOsJfPOQaJJLGfJvwnFEeBYB6RZddhfKBzTX/XruSlHcF857XhMugDrEuxQ9nmek2yk2QnhRX7tvEEFnq6TPDgZjqLXpVU2wUxP9ivgtkhD0v7bJ1ryq9vQtItosGf4SqE+JnmH/Wm5Q91d4SMHZiGsICAMwEbSE7JseQXuZVO6n8j0zFp3NvGZSJEuT7/ltuog4EhZMTjd5ZbizDdj3awD3/dRA/3qSM8yvc3d6mHrBRQO8Xr4vslvHbsw06i+aVz6ra3yub+Ey7dlQ9xWmE6kk97ai8Zyq8PAcZWk+lBkqz9eFJReou9J+c/47iZSIFf70cr7aB1/U8/bEcL7/6Fx3/838PIejhwwhyrIbwSRR9SP6AYzAe+j+GC6hNXuBYa4bw6CiM5ZljhdBlXGwbDdmG1xC+M2ubDwWLNSAfV9qMFj4OgefalJbm8UUUR2DcgpSifH8Ieqoyew/2EamWctOCtWei/D0YAWYW35fBHq00P6cn9bkLsS7pV+dxhpUliEMH4TZW0X1+OU/sxo/B0WOBQ19G6wgBUWOZqAnVm9mHf1h78h72SXmU+IAJjmz7P4DAOeO/nWLAfiXDyTPzR0Us+g59OImnnleQug=
